name: api_project_uas
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.2 <3.1.2"

dependencies:
  args: ^2.0.0
  intl: ^0.18.1
  crypto: ^3.0.3
  mysql1: ^0.20.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  string_validator: ^1.0.2

dev_dependencies:
  http: ^1.1.0
  lints: ^3.0.0
  test: ^1.15.0
